### ISSUE TITLE
500 Error: Cannot write to a secondary

### ISSUE THREAD

**Issue by grdryn** [e14n/pump2status#3]
I guess this might be something to do with mongodb replication?

```
Express
500 Error: Cannot write to a secondary
     at canCheckoutWriter (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/connection/server.js:696:12)
    at Server.checkoutWriter (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/connection/server.js:711:16)
    at __executeInsertCommand (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/db.js:1719:38)
    at Db._executeInsertCommand (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/db.js:1808:5)
    at insertAll (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/collection.js:330:13)
    at Collection.insert (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/collection.js:92:3)
    at MongoDatabank.create (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/lib/mongodb.js:193:14)
    at MongoDatabank.getCollection (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/lib/mongodb.js:76:9)
    at MongoDatabank.create (/opt/pump2status/node_modules/databank/node_modules/databank-mongodb/lib/mongodb.js:188:10)
    at DatabankObject.subClass.Cls.create (/opt/pump2status/node_modules/databank/lib/databankobject.js:165:28)
    at Function.RequestToken.beforeCreate (/opt/pump2status/models/requesttoken.js:51:5)
```

**Comment by evanp** [comment]
I think this is fixed now.
